---
 - hosts: 127.0.0.1
   gather_facts: no
   user: root
   
   tasks:
   - name: Remove Packages
     apt: name={{ item }} state=absent
     with_items:
     - tor
     - torchat
     - torsocks
     - vidalia
     - dopewars
     - tor-geoipdb
     - unity-webapps-facebookmessenger
     - unity-webapps-qml-examples
     - chromium-browser
        
   - stat: path=/etc/post_cart.sh
     register: st
     
   - name: copy Firefox preference file
     copy: src=/usr/share/swsd/ansible/syspref.js dest=/etc/firefox owner=root group=root mode=0644
     when: not st.stat.exists
     
   - name: delete firefox preference file
     file: path=/etc/firefox/syspref.js state=absent
     when: st.stat.exists
     
   - name: Update url in Ansible file
     replace: path=/usr/share/swsd/ansible_swsd.sh regexp='www.swsd.k12.pa.us' replace='swweb.swsd.k12.pa.us'
