---
 - hosts: 127.0.0.1
   gather_facts: no
   user: root
   
   tasks:
   - name: Remove Packages
     apt: name={{ item }} state=absent
     with_items:
     - tor
     - torchat
     - torsocks
     - vidalia
     - dopewars
     - tor-geoipdb
     - unity-webapps-facebookmessenger
     - unity-webapps-qml-examples
     - chromium-browser
        
   - name: copy Firefox preference file
     copy: src=/usr/share/swsd/ansible/syspref.js dest=/etc/firefox owner=root group=root mode=0644
