---
 - hosts: 127.0.0.1
   gather_facts: no
   user: root
   
   tasks:
   - name: Remove Packages
     apt: name={{ item }} state=absent
     with_items:
     - tor
     - torchat
     - torsocks
     - vidalia
     - dopewars
     - tor-geoipdb
     - unity-webapps-facebookmessenger
     - unity-webapps-qml-examples
     - chromium-browser
